#!/usr/bin/env bash
# installs nginx and configures it on a remote server
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
service nginx start
echo "Hello Word" >> /var/www/html/index.nginx-debian.html
