#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

apt-get update
apt-get install haproxy


# frontend myfrontend
#   mode http
#   bind *:80
#   default_backend web_servers

# backend web_servers
#   mode http
#   balance roundrobin
#   server 4255-web-01 54.242.35.218:80
#   server 4255-web-02 50.16.118.128:80

sed -i "$ a myfrontend\n\tbind *:80\n\tmode http\n\tdefault_backend web_servers\n" /etc/haproxy/haproxy.cfg
sed -i "$ a backend web_servers\n\tbalance roundrobin\n\tserver web1 54.242.35.218:80 check\n\tserver web2 50.16.118.128:80 check" /etc/haproxy/haproxy.cfg

sudo service haproxy start
