#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
hour=0
while (( hour < 13 ))
do
	echo "Hour: $hour"
	(( hour++ ))
	min=1
	while (( min < 60 ))
	do
		echo $min
		(( min++ ))
	done
done
